### ISSUE TITLE
Trying to get a UPNP lease with an infinite timeout triggers a delete instead.

### ISSUE THREAD

**Issue by Vagabond** [benoitc/erlang-nat#5]
My home router, a linksys nighthawk R700P only supports permanent leases:

```
UPNP SOAP error: {ok,{{"HTTP/1.1",500,"Internal Server Error"},[{"server","Linux/2.6.12 UPnP/1.0 NETGEAR-UPNP/1.0"},{"content-length","438"},{"content-type","text/xml"},{"ext",[]}],"<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">\r\n<s:Body>\r\n<s:Fault>\r\n<faultcode>s:Client</faultcode>\r\n<faultstring>UPnPError</faultstring>\r\n<detail>\r\n<UPnPError xmlns=\"urn:schemas-upnp-org:control-1-0\">\r\n<errorCode>725</errorCode>\r\n<errorDescription>OnlyPermanentLeasesSupported</errorDescription></UPnPError>\r\n</detail>\r\n</s:Fault>\r\n</s:Body>\r\n</s:Envelope>\r\n"}}
```

However, when I try to get an infinite lease using a timeout of 0, the nat code tries to do a delete instead:

https://github.com/benoitc/erlang-nat/blob/master/src/natupnp_v1.erl#L129

Is this intentional? How can I obtain an infinite lease?

**Comment by benoitc** [comment]
That was a convenient wrapper. Rereading the spec I think we should rather default to 0 when no duration is given instead of deleting it. Same for upnv v2 . Thoughts?

**Comment by Vagabond** [comment]
I'm torn, I hate things littering up my router with infinite leases, but infinite timeouts seem to work more consistently.

Certainly we need a way to be able to *request* infinite timeouts, at least. Maybe add a new clause where you can pass `infinity` as a timeout value?

**Comment by macpie** [comment]
I have created a PR #8  for this.

**Comment by benoitc** [comment]
#8 have been merged :) thanks!
